#!/bin/sh -e

## Branches
DWM_VERSION=138b405f0c8aa24d8a040cc1a1cf6e3eb5a0ebc7      # 12 Jul 2020
ST_VERSION=2ec571a30c0c3b1a17f6b3631c80d573582f59a1       # 18 Jul 2021
DMENU_VERSION=1a13d0465d1a6f4f74bc5b07b04c9bd542f20ba6    # 02 Sep 2020
TABBED_VERSION=dabf6a25ab01107fc1e0464ee6a3e369d1626f97   # 12 May 2020
SURF_VERSION=d068a3878b6b9f2841a49cd7948cdf9d62b55585     # 08 Feb 2019
SENT_VERSION=2649e8d5334f7e37a1710c60fb740ecfe91b9f9e     # 13 May 2020
SLOCK_VERSION=35633d45672d14bd798c478c45d1a17064701aa9    # 25 Mar 2017

export PREFIX=${HOME}/.local
export CFLAGS='-O2 -pipe -fstack-protector-strong'
export LDFLAGS=-s

usage() {
    >&2 echo 'Usage: ./build.sh [dwm] [st] [dmenu] [tabbed] [surf] [slock]'
    exit 1
}

clone() {
    cd $1
    [ -d $1 ] || git clone git://git.suckless.org/$1
    cd $1
    git clean -df
    git fetch --all
    git reset --hard $2
    cd "$START_PWD"
}

[ "$1" ] || usage

START_PWD=$(dirname "$0")
[ "$START_PWD" = . ] && START_PWD=$PWD
for name ; do
    cd "$START_PWD"

    case $name in
        st) clone $name $ST_VERSION ;;
        dwm) clone $name $DWM_VERSION ;;
        dmenu) clone $name $DMENU_VERSION ;;
        surf) clone $name $SURF_VERSION ;;
        tabbed) clone $name $TABBED_VERSION ;;
        sent) clone $name $SENT_VERSION ;;
        slock) clone $name $SLOCK_VERSION ;;
        *) usage
    esac

    cd $name
    cd $name

    ls ../patches | \
    while read -r patch ; do
        printf '\n%s\n\n' "===> applying $patch..."
        patch -l -i ../patches/$patch
    done

    cp -f ../cfg/config.h . 2>/dev/null ||:
    cp -f ../cfg/config.mk . 2>/dev/null ||:
    cp -f ../cfg/Makefile . 2>/dev/null ||:
    case $name in
        slock)
            >&2 printf '\n%s\n' 'Need to install to /usr/local due to suid:'
            case $(uname) in
                Linux)
                    sudo make -s PREFIX=/usr/local install
                    sudo chmod u+s /usr/local/bin/slock
                    ;;
                FreeBSD)
                    sudo make -s PREFIX=/usr/local install
                    sudo chmod u+s /usr/local/bin/slock
                    ;;
                OpenBSD)
                    doas make -s PREFIX=/usr/local install
                    doas chmod u+s /usr/local/bin/slock
            esac
            ;;
        *)
            make -s clean
            make -s -j${NPROC:-1} CC=${CC:-cc}
            make -s PREFIX="$PREFIX" install
            make -s clean
        ;;
    esac
done
